spring:
  application:
    name: securityDemo
  security:
    user:
      name: admin
      password: 123
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  app:
    jwtSecret: mySecretKey123!#912738
    jwtExpirationMs: 300000000000000000000000000000